main: @project.groupId@.@project.artifactId@.@project.name@
name: @project.name@
authors: [ Ome_R,Valentina_pro ]
version: "@project.version@"
description: "@project.description@"
api-version: '1.13'
depends: CoreProtect
softdepend: [AcidIsland, ASkyBlock, BentoBox, Factions, FactionsX, PlotSquared, GriefPrevention, Towny, Villages]
commands:
  wildinspect:
    description: Reload configuration files
    aliases: [wi]
permissions:
  wildinspect.reload:
    description: Access to reload configuration files